#!/bin/bash
# This script generates an Ansible inventory file for the I2PC training environment.

# Input CSV file generated by levantar_muchas.sh
INPUT_MACHINES="./instances_output.csv"

# Output inventory file
INVENTORY_FILE="./inventory"

# Common string to append to each inventory line
INVENTORY_COMMON_STRING="ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/i2pc-training.pem"

# Check if the input CSV exists
if [[ ! -f $INPUT_MACHINES ]]; then
  echo "Error: Input CSV file '$INPUT_MACHINES' not found."
  exit 1
fi

# Clear or create the inventory file
> $INVENTORY_FILE

echo -e "[servers]" >> $INVENTORY_FILE

# Read the CSV file line by line, skipping the header
tail -n +2 "$INPUT_MACHINES" | while IFS=', ' read -r INSTANCE_NAME ELASTIC_IP; do
  # Write the IP and common string to the inventory file
  echo "$INSTANCE_NAME ansible_host=$ELASTIC_IP $INVENTORY_COMMON_STRING" >> $INVENTORY_FILE
done

# Append the additional text at the end of the inventory file
echo -e "\n[servers:vars]\nansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> $INVENTORY_FILE

echo "Ansible inventory generated in $INVENTORY_FILE"
