#!/bin/bash

# Input CSV file generated by levantar_muchas.sh
INPUT_MACHINES="./instances_output.csv"
INPUT_LICENSES="./license_list.txt"

# Output file for the key:value rows
OUTPUT_FILE="./playbook_cryosparc_dictionary.txt"

# Check if the input CSV exists
if [[ ! -f $INPUT_MACHINES ]]; then
  echo "Error: Input CSV file '$INPUT_MACHINES' not found."
  exit 1
fi
if [[ ! -f $INPUT_LICENSES ]]; then
  echo "Error: Input CSV file '$INPUT_LICENSES' not found."
  exit 1
fi

# Clear or create the output file
> $OUTPUT_FILE

# Populate a list with the available licenses
LICENSES=()
while IFS= read -r LICENSE; do
  LICENSES+=("$LICENSE")
done < "$INPUT_LICENSES"

# Check if there are enough licenses for the machines
LICENSE_COUNT=${#LICENSES[@]}
MACHINE_COUNT=$(tail -n +2 "$INPUT_MACHINES" | wc -l)

if (( LICENSE_COUNT < MACHINE_COUNT )); then
  echo "Error: Not enough licenses for the number of machines."
  echo "Licenses available: $LICENSE_COUNT, Machines: $MACHINE_COUNT"
  echo "Please add more licenses to the license list."
  exit 1
fi

# Read the CSV file line by line, skipping the header
INDEX=0
tail -n +2 "$INPUT_MACHINES" | while IFS=',' read -r INSTANCE_NAME ELASTIC_IP; do
  # Assign a license from the LICENSES array
  LICENSE=${LICENSES[$INDEX]}
  INDEX=$((INDEX + 1))

  # Write the key:value pair to the output file
  echo "$INSTANCE_NAME: \"$LICENSE\"" >> $OUTPUT_FILE
done

echo "License list generated in $OUTPUT_FILE"
